@host=localhost:3001

### 
GET http://{{host}}/cal
content-type: application/json

### 
POST http://{{host}}/cal
content-type: application/json

{
    "lowerNumber" : "10",
    "higherNumber" : "55"
}

